#!/bin/sh
rm -f colors.jar
touch 'IntelliJ IDEA Global Settings'

zip colors.jar colors -r 'IntelliJ IDEA Global Settings'

rm -f 'IntelliJ IDEA Global Settings'


rm -f options/*.jar
touch options/'IntelliJ IDEA Global Settings'
mkdir -p options/colors
mkdir -p options/options

for path in $(find options -name '*.theme.xml'); do
    file=$(basename "$path")
    name="${file%.*.*}"
    cp colors/$name.icls options/colors
    cp options/$file options/options/material_custom_theme.xml
    cp options/$name.accent.xml options/options/material_theme.xml
    cp options/$name.scheme.xml options/options/colors.scheme.xml
    cd options; zip -r $name.jar options colors 'IntelliJ IDEA Global Settings'; cd ../
done

rm -f options/*.xml
rm -f options/'IntelliJ IDEA Global Settings'
rm -rf options/colors
rm -rf options/options
